---
title: "case study"
date: 10-8-2019
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(tidyverse)
library(leaflet)
```


```{r airbnb}
library(p8105.datasets)

data(nyc_airbnb) 

# view nyc_airbnb 
str(nyc_airbnb)

nyc_airbnb %>% view

nyc_airbnb %>%
  count(room_type)


#Does rating vary by neighborhood, room type, or both?
nyc_airbnb=
nyc_airbnb %>% 
  mutate(
    stars = review_scores_location / 2,
    borough = neighbourhood_group)
    

#How is price related to other variables?
#Where are rentals located?
```

```{r}

nyc_airbnb %>% 
  mutate(neighbourhood= as.factor(neighbourhood)) %>% 
  filter(borough == "Manhattan") %>% 
  ggplot(aes(x = price, y = neighbourhood))+
  geom_violin()
    
```
```{r}

nyc_airbnb %>% 
  mutate(neighbourhood= as.factor(neighbourhood)) %>% 
  filter(borough == "Manhattan") %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, 
                                     price, na.rm = TRUE)) %>% 
  ggplot(aes(x = price, y = neighbourhood))+
  geom_violin()
```


```{r}
nyc_airbnb %>% 
  group_by(borough, room_type) %>% 
  summarize(med_price = median(price , na.rm = TRUE))
```

```{r}
nyc_airbnb %>% 
  filter(borough  == "Staten Island", room_type == "Shared room") %>% view


nyc_airbnb %>% 
  count(borough, room_type) %>% 
  pivot_wider(
    names_from = room_type,
    values_from = n
  )
```

```{r}
nyc_airbnb %>% 
  group_by(neighbourhood_group, neighbourhood) %>% 
  summarize(
    mean_price = mean(price, na.rm = TRUE),
    mean_review = mean(review_scores_location, na.rm = TRUE)
  ) %>% 
  ggplot(aes(x = mean_review, y = mean_price))+
  geom_point()+
  facet_grid(~neighbourhood_group)
```

```{r}
nyc_airbnb %>% 
  count(neighbourhood)

nyc_airbnb %>% 
  filter(neighbourhood == "Astoria") %>% 
  ggplot(aes(x = stars, y = price))+
  geom_point()
```

```{r}

nyc_airbnb %>% 
  ggplot(aes(x = lat, y = long, color = neighbourhood_group))+
  geom_point()
```

```{r}
nyc_airbnb %>% 
  filter(
    borough == "Manhattan",
    price < 1000) %>% 
  ggplot(aes(x = lat, y = long, color = price))+
  geom_point(alpha = 0.2)+
  facet_grid(~room_type)
```

```{r}
nyc_airbnb %>% 
  filter(
    borough == "Manhattan" ,
    price > 2000) %>% 
  leaflet() %>% 
  addTiles() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircleMarkers(~lat,~long,
                   color = ~pal(stars), 
                   radius = 1)
 
  
```

```{r}

```

